# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luis Gerardo
title: Software Developer
email: Luis.briceno4733@alumnos.udg.mx
website:

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ruisuhq
github_username: ruisuhq
instagram_username: ruisuhq
linkedin_username:
youtube_username: "@ruisuhq"

# Additional icon links
additional_links:

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm:
# gtag:
# google_analytics:

# About Section
# about_title: About Me
about_profile_image: images/pp.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey there! I'm Luis Gerardo, a passionate software developer who loves coding and creating useful things. With a knack for Python, Django, and agile project management, I’ve been working on projects like management systems for small businesses, web platforms for rental contracts, and tailored solutions for local companies.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Stardew Valley Web Crawler
        link: https://github.com/ruisuhq/Stardew-Crawler
        quote: >
          A handy tool to gather data and calculate the most profitable crops in Stardew Valley.
        description: |
          This project blends web scraping and data analysis to create optimized agricultural summaries. Pretty cool, right?

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Small Project Management
        link: # Add project or description link here
        sub_title: Software Developer
        caption: 2022 - Present
        quote: >
          Helping small businesses go digital and organize their operations like pros.
        description: |
          Developed inventory systems, sales modules, and integrated thermal printer support. Simple yet effective solutions for real-world problems.

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Guadalajara
        caption: Center for Exact Sciences and Engineering
        sub_title: Software Engineering
        quote: >
          A solid mix of software development, cybersecurity, and agile methodologies.
        description: |
          I dove into advanced algorithms, web applications, and more during my studies. It’s been an exciting ride!

  - title: A Bit About Me
    layout: list
    content:
      - layout: left
        title: Things I Love
        description: |
          When I'm not coding, I’m into:
          - Video games
          - Music
          - Tech innovations
          - Romantic comedies (yes, really!)

# Footer
footer_show_references: false
# references_title: References available upon request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
